// import { Inter } from "next/font/google";
// import "../styles/globals.css";
// import Navbar from '@/Components/Navbar';
// import Footer from '@/Components/Footer';
// //import { renderForm } from "@/Components/Button";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar />
//         {/* //{renderForm} */}
//         {children}
//         <Footer />
//         </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from '@/Components/Navbar';
import Footer from '@/Components/Footer';
import { CartProvider } from '../Components/CartContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className} id="root">
        <CartProvider>
        <Navbar />
        </CartProvider>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
